### ISSUE TITLE
library not found for -lRNDeviceInfo-tvOS

### ISSUE THREAD

**Issue by nyngwang** [rebeccahughes/react-native-device-info#258]
i got the error message when run `react-native run-ios`:

ld: library not found for -lRNDeviceInfo-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

please help

**Comment by stackia** [comment]
Seems like a bug caused by `react-native link`
You can manually delete `libRNDeviceInfo-tvOS.a` in Xcode -> [Your iOS build target] -> Build Phrases -> Link Binary with Libraries.

**Comment by nyngwang** [comment]
@stackia  Thank you, this is exactly how i solved it! :)

**Comment by tmaly1980** [comment]
@rebeccahughes How hard is this to fix? I just downloaded a fresh version and still experiencing this?

**Comment by rogerkerse** [comment]
Not a sustainable solution of deleting it manually for every project and every person that tries to install it.

**Comment by hahtml** [comment]
@stackia Thanks a lot, this solution helped me finally.

**Comment by uikolas** [comment]
@rogerkerse Yes. Fix is in progress for this: https://github.com/facebook/react-native/issues/13783

**Comment by SuvarnaMachappanavar** [comment]
When would this be fixed?...I just downloaded this yesterday ..and still seems like the issue is not fixed....

**Comment by afilp** [comment]
Just had the same problem, not fixed yet.

**Comment by fryck** [comment]
The same for me, is there a clean solution please ? :)

**Comment by jbrodriguez** [comment]
I thought this was fixed with 0.14.0, but it's still there

**Comment by machour** [comment]
Confirmed, the issue is still present in 0.14.0.

This is a react-native issue and it seems to have been fixed 5 days ago:
   https://github.com/facebook/react-native/commit/a63fd378a47173cc9f750e9980f18dc12dd7ea51

Please correct me if I'm wrong, but I don't think this really is an issue with react-native-device-info. (or at least, there's nothing we can do about it beside documenting this in a troubleshooting section?)

**Comment by machour** [comment]
We're almost there: https://github.com/facebook/react-native/releases/tag/v0.53.0

**Comment by lmichailian** [comment]
I have this issue with v0.53.0 

`Ld /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/powergymapp.app/powergymapp normal arm64
    cd /Users/lucas/Code/powergymapp/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -L/Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos -F/Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos -filelist /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Intermediates.noindex/powergymapp.build/Debug-iphoneos/powergymapp.build/Objects-normal/arm64/powergymapp.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -Xlinker -object_path_lto -Xlinker /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Intermediates.noindex/powergymapp.build/Debug-iphoneos/powergymapp.build/Objects-normal/arm64/powergymapp_lto.o -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -ObjC -lc++ /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTBlob.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTAnimation.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libReact.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTAnimation.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTActionSheet.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTGeolocation.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTImage.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTLinking.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTNetwork.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTSettings.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTText.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTVibration.a /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/libRCTWebSocket.a -lRNCamera -lRNDeviceInfo -lRNDeviceInfo-tvOS -Xlinker -dependency_info -Xlinker /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Intermediates.noindex/powergymapp.build/Debug-iphoneos/powergymapp.build/Objects-normal/arm64/powergymapp_dependency_info.dat -o /Users/lucas/Library/Developer/Xcode/DerivedData/powergymapp-fsbtlkofxlrejncnbapjlevirwox/Build/Products/Debug-iphoneos/powergymapp.app/powergymapp

ld: library not found for -lRNDeviceInfo-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by machour** [comment]
Documented this react-native bug in the [troubleshooting](https://github.com/rebeccahughes/react-native-device-info#troubleshooting) section of README.md

**Comment by lmichailian** [comment]
I resolve this deleting my project and create a new from zero and instead npm now I use yarn.

**Comment by liuqiiiiiii** [comment]
`
ld: library not found for -lRNDeviceInfo-tvOS

clang

: error: linker command failed with exit code 1 (use -v to see invocation)





** BUILD FAILED **


The following build commands failed:
        Ld /Users/a11/Componey/javashop-react_native/ios/build/Build/Products/Debug-iphonesimulator/javashop.app/javashop normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/javashop.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/javashop.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

**Comment by liuqiiiiiii** [comment]
I'm in terrible shape here!
