### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by feadrick** [rebeccahughes/react-native-device-info#510]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.24.0 |
| Affected OS | android   |
| OS Version  |  windows 8.1  |

## Current behavior
undefined is not an object (evaluating 'RNDeviceInfo.brand')

**Comment by borgogelli** [comment]
+1

**Comment by JackHull** [comment]
+1

**Comment by markoliverbrawn** [comment]
I'm also getting this - for any method called (on version 0.22.2). Not sure if it's important, but I'm using the Android emulator.

**Comment by JackHull** [comment]
Got this fixed by linking, and then re-buildinf the app.

**Comment by christianscheuer** [comment]
@JackHull by linking you mean `react-native link react-native-device-info`?
That doesn't solve it for me. Anyone else who knows why this happens?

**Comment by GitHubGreg** [comment]
I'm also having this problem. I am using Expo SDK 29.

**Comment by JoeM-RP** [comment]
I was able to get around this by following the [manual linking steps (without cocoapods)](https://github.com/rebeccahughes/react-native-device-info#manual) outlined in the README, copied here for convenience. 

In XCode, in the project navigator:
- Right click the _Libraries_ folder
- Add Files to [your project's name]
- Go to node_modules/react-native-device-info
- Add the .xcodeproj file

In XCode, in the project navigator, select your project.
- Add the libRNDeviceInfo.a from the deviceinfo project to your project's Build Phases ➜ Link Binary With Libraries
- Click .xcodeproj file you added before in the project navigator and go the Build Settings tab. Make sure All option is toggled on (instead of Basic).
- Look for Header Search Paths and make sure it contains both $(SRCROOT)/../react-native/React and $(SRCROOT)/../../React
- Mark both as recursive (should be OK by default).

**Comment by mikehardy** [comment]
@machour closable - another failure to install correctly, but the library definitely works according to instructions (I just installed it...)
